#!/bin/sh

# An example hook script to verify what is about to be pushed.  Called by "git
# push" after it has checked the remote status, but before anything has been
# pushed.  If this script exits with a non-zero status nothing will be pushed.

### Linting
printf "\n%s\n" "Pre-push hook activated."
start_lint=$(date +%s)
printf "%s\n" "Linting..."
yapf -ir . --exclude '*ipynb*' --exclude .venv
isort . --atomic --skip-glob "*ipynb*" --line-width 99
end_lint=$(date +%s)
printf "%s\n" "Linting completed for "$(($end_lint-$start_lint))" seconds."
coverage run -m pytest -x
coverage report -m
